In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((5,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [6]:
x = np.full((10,20),4)

In [7]:
x.ndim

2

In [8]:
x.shape

(10, 20)

In [9]:
x.size

200

In [10]:
x.dtype

dtype('int32')

In [11]:
x[0,1]

4

In [12]:
x[0,1]=3

In [13]:
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [14]:
x[0,1]=3.14

In [15]:
x

array([[4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [16]:
x = np.random.randint(10, size=6)

In [17]:
x

array([8, 3, 7, 8, 3, 2])

In [18]:
x[0:2]

array([8, 3])

In [19]:
x[0::2]

array([8, 7, 3])

In [20]:
def calcule_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

In [30]:
tableau_large = np.random.randint(1,10, size=1000000)

In [31]:
%timeit calcule_inverse(tableau_large)

2.91 s ± 49.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit (1.0/tableau_large)

3.68 ms ± 180 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
x

array([8, 3, 7, 8, 3, 2])

In [37]:
x = np.zeros((4,3))

In [38]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
x[1,2]

0.0

In [41]:
x[0:3,0:2]

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
x = np.random.random((5,3))

In [43]:
x

array([[0.07937098, 0.70277122, 0.19959163],
       [0.01070007, 0.07693048, 0.35985038],
       [0.06063736, 0.02195614, 0.23367482],
       [0.66675362, 0.76337993, 0.12740619],
       [0.99676924, 0.56759353, 0.11488598]])

In [44]:
x[0:3,0:2]

array([[0.07937098, 0.70277122],
       [0.01070007, 0.07693048],
       [0.06063736, 0.02195614]])

In [45]:
y = np.array([1, 2, 3])
z = np.array([3, 2, 1])
np.concatenate([y, z])

array([1, 2, 3, 3, 2, 1])

In [47]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
x = np.random.random((2,1))
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.hstack([x, grid])

array([[0.81456584, 9.        , 8.        , 7.        ],
       [0.47826636, 6.        , 5.        , 4.        ]])

In [52]:
x = np.random.rand(3,3)
x > 0.5

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [53]:
np.where(x > 0.5)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [54]:
x.sum(axis=0)

array([1.93409895, 2.34896459, 2.25916158])

In [55]:
x.sum(axis=1)

array([1.79398781, 2.32479356, 2.42344375])

In [60]:
np.percentile(x,10)

0.4619482152131952

In [62]:
np.arange(3)

array([0, 1, 2])

In [63]:
np.arange(3)[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [69]:
a = np.arange(3)
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
c=a+b

In [70]:
c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [74]:
c>1

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [84]:
c[(c>1) & (c%2==0)]

array([2, 2, 2, 4])